//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Indicador
    {
        public int Id { get; set; }
        public Nullable<int> PlanificacionId { get; set; }
        public string Accion { get; set; }
        public string Conocimiento { get; set; }
        public string Condiciones { get; set; }
    
        public virtual Planificacion Planificacion { get; set; }
    }
}
