//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Planificacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Planificacion()
        {
            this.Indicador = new HashSet<Indicador>();
        }
    
        public int Id { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> AsignaturaId { get; set; }
        public string Curso { get; set; }
        public int AnioEscolar { get; set; }
        public string Tema { get; set; }
        public string CompetenciasFundamentales { get; set; }
        public string CompetenciasEspecificas { get; set; }
        public string Escenario { get; set; }
        public System.DateTime Fecha { get; set; }
        public Nullable<int> MetodoId { get; set; }
        public Nullable<int> SistematizacionId { get; set; }
        public Nullable<int> TrabajoId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Indicador> Indicador { get; set; }
        public virtual Metodo Metodo { get; set; }
        public virtual Trabajo Trabajo { get; set; }
        public virtual Sistematizacion Sistematizacion { get; set; }
        public virtual Trabajo Trabajo1 { get; set; }
    }
}
